### ISSUE TITLE
Artisan - RuntimeException 

### ISSUE THREAD

**Issue by dementor4842** [gamingdotme/opensource-casino-v10#1]
Hello im having this problem on my VPS, how can i solve the problem?

Thank you all for the good job

`[root@srv19924945 CASINO]# sudo php artisan serve

   Symfony\Component\Process\Exception\RuntimeException 

  The provided cwd "/www/wwwroot/xxxxxxxxx.com/CASINO/public" does not exist.

  at vendor/symfony/process/Process.php:346
    342▕             }
    343▕         }
    344▕ 
    345▕         if (!is_dir($this->cwd)) {
  ➜ 346▕             throw new RuntimeException(sprintf('The provided cwd "%s" does not exist.', $this->cwd));
    347▕         }
    348▕ 
    349▕         $this->process = @proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $envPairs, $this->options);
    350▕ 

      +15 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
[root@srv19924945 CASINO]# `

**Comment by gamingdotme** [comment]
Old comment I know, but basically you just have paths wrong
In our example we put app in public_html
example 
/home/user/public_html    <--- this is your HTML, WWW , Webroot 
casino outside for security
/home/user/casino
