### ISSUE TITLE
socket error

### ISSUE THREAD

**Issue by by029** [gamingdotme/opensource-casino-v10#6]
![image](https://github.com/gamingdotme/opensource-casino-v10/assets/23432802/74d9e582-2b57-4103-a7b7-7996c5fd865b)

What is the reason why a socket error occurs when opening a fishing program?

**Comment by gamingdotme** [comment]
that is not enough to diagnose
However : pm2 logs     would be showing more specific errors
hardcoded sessions / different pm2 application paths or changed (again hardcoded in my example )
For such specific games, ask in discord where u got the games, related sockets info should be there, usually a small fix

**Comment by by029** [comment]
Because I cannot subscribe to related services through discord in my area, is there any other way to obtain it?

**Comment by gamingdotme** [comment]
Subscription is not obligatory, you can join the free sections and see few had same errors
Again, i still answered you above, you need pm2 logs , your issue is websockets [socketclose] 
chrome will not show you backend log errors .

**Comment by by029** [comment]
I don’t have a payment method on the discord platform, but I really need the game download package. Can I pay you USDT and get the download address of the game resource package?

**Comment by gamingdotme** [comment]
We are repeating same things, and you are not reading
JOIN FOR FREE, ask Mods or directly @sarcasm in discord, yes you can arrange game file svia usdt or whatever if discord doesnt work
And you benefit from many addons in discord for this plugin like sports, pragmatic games, apis, etc
