### ISSUE TITLE
The provided cwd "%s" does not exist.

### ISSUE THREAD

**Issue by poterasal** [gamingdotme/opensource-casino-v10#7]
root@777play:/www/wwwroot/777play/CASINO# sudo php artisan serve

   Symfony\Component\Process\Exception\RuntimeException

  The provided cwd "/www/wwwroot/777play/CASINO/public" does not exist.

  at vendor/symfony/process/Process.php:344
    340▕             }
    341▕         }
    342▕
    343▕         if (!is_dir($this->cwd)) {
  ➜ 344▕             throw new RuntimeException(sprintf('The provided cwd "%s" does not exist.', $this->cwd));
    345▕         }
    346▕
    347▕         $this->process = @proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $envPairs, $this->options);
    348▕

      +15 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

I modifyed the server.php with the actually public_html where its located and same error.

My server.php : 

<?php

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */

$uri = urldecode(
    parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)
);

// This file allows us to emulate Apache's "mod_rewrite" functionality from the
// built-in PHP web server. This provides a convenient way to test a Laravel
// application without having installed a "real" web server software here.
if ($uri !== '/' && file_exists(__DIR__.'/www/wwwroot/777play'.$uri)) {
    return false;
}

require_once __DIR__.'/www/wwwroot/777play/index.php';

**Comment by gamingdotme** [comment]
You do not have to modify anything, you obviously uploaded to wrong structure, just upload files as is to your current www or public_html directory.
 And you can join discord for an active community for support.

**Comment by alexanderbkl** [comment]
there is no "public" folder, the creator of this repo deleted it on purpose making it useless
